name: Build manifest
on:
  push:
    branches: [ main, master ]
    paths:
      - "assets/**"
      - "scripts/generate-manifest.mjs"
      - ".github/workflows/manifest.yml"
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: node scripts/generate-manifest.mjs
      - name: Commit manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manifest.json"
          file_pattern: data/manifest.json
